services:
  db:
    image: imresamu/postgis:17-3.5
    restart: always
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cowlesie
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: